apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  CONNECTION_STRING_VALUE: bW9uZ29kYjovL2FkbWluOmFkbWluMTIzQDMuMjE1LjE3OS43MzoyNzAxNy9yZXN0YXVyYW50c19yZXZpZXdzP2F1dGhTb3VyY2U9YWRtaW4=


